baseURL = "https://gleland.github.io"
languageCode = "en-us"
title = "Garrett Leland"
#theme="hyde"
markup = "org"
PygmentsCodeFences = true
PygmentsStyle = "friendly"


  [[menu.posts]]
    identifier = "posts"
    name = "Posts"
    pre = "<i class='far fa-comment'></i>"
    url = "/posts"

  [[menu.main]]
    identifier = "github"
    name = "Github"
    pre = "<i class='fab fa-github'></i>"
    url = "https://github.com/Gleland"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    pre = "<i class='fas fa-envelope'></i>"
    url = "mailto:garrett.leland.thompson@gmail.com"

  [[menu.main]]
    identifier = "linkedIn"
    name = "LinkedIn"
    pre = "<i class='fab fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/gthompson80/"

[params]
  themeColor = "theme-base-gt"
  layoutReverse = true
  description="Support Engineer\n Amazon"
  copyright= "All opinions are my own."

